services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: lms
    ports:
      - "3306:3306"