services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    networks:
      - lms

  database:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: lms
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - lms
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
    depends_on:
      - database
    networks:
      - lms

networks:
  lms:
    driver: bridge
volumes:
  db: