apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lms.name }}
spec:
  replicas: {{ .Values.lms.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.lms.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.lms.name }}
    spec:
      initContainers:
        - name: init-container
          image: {{ .Values.lms.image }}
          command:
            - "sh"
            - "-c"
            - |
              cp -r /app/. /shared-code/
          volumeMounts:
            - name: shared-code
              mountPath: /shared-code/
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
          env:
            - name: NGINX_ENTRYPOINT_QUIET_LOGS
              value: "1"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-code
              mountPath: /app

        - name: library-management-system
          image: {{ .Values.lms.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.lms.containerPort }}
          env:
            - name: FLASK_APP
              value: "app.py"
            - name: FLASK_ENV
              value: "development"
          volumeMounts:
            - name: shared-code
              mountPath: /app
      volumes:
        - name: shared-code
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lms.service.name | quote }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.lms.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.lms.name | quote }}
  ports:
    - port: {{ .Values.lms.service.port }}
      targetPort: {{ .Values.lms.service.targetPort }}