apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lms-deployment
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: lms-deployment
  endpoints:
  - port: metrics