name: Build and Push Docker Image
on:
  workflow_dispatch: # allows you to trigger the workflow manually
  # I disable push because this is for testing
  # push:
  #   branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # the runner that executes the workflow
    steps:
      - uses: actions/checkout@v3 # checkout the repository

      - name: Login to Docker Hub
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # your username on Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }} # your password on Docker Hub

      - name: Build and push
        uses: docker/build-push-action@v7.1.0
        with:
          context: . # the context is the current directory
          push: true # push the image to Docker Hub
          tags: ahmedafk404/library-management-system:latest # the name of the image on Docker Hub

  selfhosted-kubernetes-deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install git
        run: sudo yum update -y && sudo yum install git -y

      - name: pull docker image
        run: sudo docker pull ahmedafk404/library-management-system:latest

      - name: clone github repo
        run: git clone https://github.com/ahmedalaa-afk/library-management-system-docker.git

      - name: print working dir
        run: pwd

      - name: apply manifest files
        run: |
          sudo kubectl apply -f library-management-system-docker/k8s/db-config.yml
          sudo kubectl apply -f library-management-system-docker/k8s/lms-deployment.yml
          sudo kubectl apply -f library-management-system-docker/k8s/mysql-deployment.yml
          sudo kubectl apply -f library-management-system-docker/k8s/pma-deployment.yml
